[2025-03-08T21:37:43.561+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-08T21:37:43.573+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_process.Init_session.postgres_connection manual__2025-03-08T21:37:41.682722+00:00 [queued]>
[2025-03-08T21:37:43.579+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_process.Init_session.postgres_connection manual__2025-03-08T21:37:41.682722+00:00 [queued]>
[2025-03-08T21:37:43.580+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-03-08T21:37:43.591+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): Init_session.postgres_connection> on 2025-03-08 21:37:41.682722+00:00
[2025-03-08T21:37:43.598+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=396) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-08T21:37:43.599+0000] {standard_task_runner.py:72} INFO - Started process 398 to run task
[2025-03-08T21:37:43.599+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'data_process', 'Init_session.postgres_connection', 'manual__2025-03-08T21:37:41.682722+00:00', '--job-id', '56', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/tmp/tmpzioms3eo']
[2025-03-08T21:37:43.600+0000] {standard_task_runner.py:105} INFO - Job 56: Subtask Init_session.postgres_connection
[2025-03-08T21:37:43.798+0000] {task_command.py:467} INFO - Running <TaskInstance: data_process.Init_session.postgres_connection manual__2025-03-08T21:37:41.682722+00:00 [running]> on host b4b16ef2f6e0
[2025-03-08T21:37:43.865+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_process' AIRFLOW_CTX_TASK_ID='Init_session.postgres_connection' AIRFLOW_CTX_EXECUTION_DATE='2025-03-08T21:37:41.682722+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-08T21:37:41.682722+00:00'
[2025-03-08T21:37:43.866+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-03-08T21:37:43.866+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-03-08T21:37:43.866+0000] {logging_mixin.py:190} INFO - Current task name:Init_session.postgres_connection state:running start_date:2025-03-08 21:37:43.574072+00:00
[2025-03-08T21:37:43.867+0000] {logging_mixin.py:190} INFO - Dag name:data_process and current dag run status:running
[2025-03-08T21:37:43.867+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-08T21:37:43.889+0000] {logging_mixin.py:190} INFO - Успешное подключение! Результат запроса: 1
[2025-03-08T21:37:43.890+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-03-08T21:37:43.898+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-08T21:37:43.899+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=data_process, task_id=Init_session.postgres_connection, run_id=manual__2025-03-08T21:37:41.682722+00:00, execution_date=20250308T213741, start_date=20250308T213743, end_date=20250308T213743
[2025-03-08T21:37:43.916+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-03-08T21:37:43.916+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-03-08T21:37:43.916+0000] {logging_mixin.py:190} INFO - Dag name:data_process queued_at:2025-03-08 21:37:41.708540+00:00
[2025-03-08T21:37:43.917+0000] {logging_mixin.py:190} INFO - Task hostname:b4b16ef2f6e0 operator:PythonOperator
[2025-03-08T21:37:43.934+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-08T21:37:44.059+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-08T21:37:44.061+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
